### ISSUE TITLE
Auth with Amazon Cognito

### ISSUE THREAD

**Issue by gedion** [Ethiopia-COVID19/Covid19.ET#21]
- Multiple level of auth.

**Comment by abelhbeyene** [comment]
Picking this one up

**Comment by abelhbeyene** [comment]
WIP branch: https://github.com/Ethiopia-COVID19/Covid19.ET/tree/feature/auth
If anyone would like to jump in and pick it over the next 12 hrs feel free just give me a heads up as soon as you do.
All you need is here: https://www.youtube.com/watch?v=bM0iisnRYUk
And here: https://aws-amplify.github.io/docs/js/authentication#amplify-project-setup
cc. @gedion @yohane55 @BisratAtSplk

**Comment by yohane55** [comment]
Ok let me try...

**Comment by yohane55** [comment]
@abel have you used Amplify CLI? or trying to configure manually?

**Comment by abelhbeyene** [comment]
@yohane55 didn't use the cli. We don't need to because cognito was already setup

**Comment by yohane55** [comment]
Ok I will add it store and you can finish it from there

**Comment by yohane55** [comment]
it says .... Unable to verify secret hash for client 654eeg4trcap5e105vvtk322ob

**Comment by yohane55** [comment]
Ok this part is done as of [b82dbda](https://github.com/Ethiopia-COVID19/Covid19.ET/commit/b82dbda70ceede65fa9cfd5258641f0df2d7b377)
