### ISSUE TITLE
Remove radial charts and replace them with a bar chart

### ISSUE THREAD

**Issue by yohannesHL** [Ethiopia-COVID19/Covid19.ET#31]
https://api.pmo.gov.et/v1/cases/

**Comment by yohannesHL** [comment]
Decided to include two bar charts in place.

![localhost_3000_ (4)](https://user-images.githubusercontent.com/9559892/78173482-bd933100-744f-11ea-8b11-467e1bbba6e4.png)

**Comment by yohane55** [comment]
@yohannesHL that is cool
