### ISSUE TITLE
Update the readme on how to contribute 

### ISSUE THREAD

**Issue by sole6** [Ethiopia-COVID19/Covid19.ET#5]
Hi,
To make a contribution easier, i think it would be nice to have simple instructions here on how to do that.

**Comment by sole6** [comment]
I still don't know how to contribute :) other than adding issues. it can still be more clear :)

**Comment by yohane55** [comment]
@sole6 sorry for the delay, this is because am doing alot, this project is less than a week old, including the backend , and I had a lot to work on.

for now you can just fork the repo and add ui components that you think are missing then create a PR, I will merge if no conflict.
