### ISSUE TITLE
Create a new account not working :  "Signup is not permitted to this user pool" error message.

### ISSUE THREAD

**Issue by dave05** [Ethiopia-COVID19/Covid19.ET#58]
![Screenshot_20200407-103310](https://user-images.githubusercontent.com/3447354/78735550-ad2bfc00-7910-11ea-8b42-e3070e9f6d0d.png)

**Comment by abelhbeyene** [comment]
@yohane55 do we want to allow users to create an account? I thought we were going have a shared login access? Maybe I am wrong...

If we do allow users to create an account we probably want to restrict that to admins or super-admins only.

@nabebe @dotmike - thoughts?
