### ISSUE TITLE
Yagegemu patients is not showing on the daily graph

### ISSUE THREAD

**Issue by YAbate** [Ethiopia-COVID19/Covid19.ET#6]

**Comment by YAbate** [comment]
sorry it is there. just hidden behind the other dots i think

**Comment by YAbate** [comment]
but it is worth sanity checking the running sums and numbers as people come in and go out. how that is reflected on the dashboard

**Comment by yohane55** [comment]
it is fixed in the next update which will be pushed late in the afternoon or in the evening.

**Comment by yohane55** [comment]
It is now fixed!
