### ISSUE TITLE
Map fails to load with `invalidKeyMapError`

### ISSUE THREAD

**Issue by bayfera** [Ethiopia-COVID19/Covid19.ET#60]
The API key used for the map seems like it is invalid and resource is not loading.
![Screen Shot 2020-04-10 at 10 49 38](https://user-images.githubusercontent.com/7300407/78978524-35312200-7b1a-11ea-9fe5-efd25a9a917f.png)

**Comment by yohane55** [comment]
Yes we wanted to use Google map and we are hoping that @dotmike will get free Gmap credit and provide API key as ENV variable on deployment server. 

But to test it on your local host you can get you api key [developers.google.com](https://developers.google.com/maps/documentation/javascript/get-api-key).
