### ISSUE TITLE
Duplicate chart for daily case status

### ISSUE THREAD

**Issue by bayfera** [Ethiopia-COVID19/Covid19.ET#61]
It seems like we have two charts that represent the same data, which is the status of cases in a particular date. 

Please close these issue if those charts represent different data.

![Screen Shot 2020-04-10 at 16 10 05](https://user-images.githubusercontent.com/7300407/78997279-8ce58280-7b46-11ea-94d9-86dbe9a4a080.png)

**Comment by yohane55** [comment]
@bayfera the above on is for hourly for current day, where as the second one is daily for the current month.
